image: registry.splentity.com/openblox/ci-build-environment/ob:latest

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  script:
    - git submodule init
    - git submodule update
    - ./prepare_ci.sh
    - ./autoconf.sh
    - ./configure --with-libopenblox=./libopenblox.pc
    - make
