image: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  script:
    - git submodule init
    - git submodule update
    - ./prepare_ci.sh
    - ./autoconf.sh
    - ./configure --with-libopenblox=./libopenblox.pc
    - make
