image: registry.splentity.com/openblox/ci-build-environment/ob:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
    - ./prepare_ci.sh
    - ./autoconf.sh
    - ./configure --with-libopenblox=./libopenblox.pc
    - make
